---

  - name: docker-compose template (base)
    local_action:
      module: template
      src: compose-base.j2
      dest: "{{playbook_dir}}/resources/base.j2"

  - name: build honeypot list
    set_fact:
      honeypots: [ "base" ]

  - name: copy authorized_keys
    authorized_key:
      user: crockpot
      key: "{{lookup('file', '{{key_path}}/tun.key.pub')}}"
      state: present
