---

  - name: docker-compose template (base)
    local_action:
      module: template
      src: compose-base.j2
      dest: "{{playbook_dir}}/resources/base.j2"

  - name: build honeypot list
    set_fact:
      honeypots: [ "base" ]

  - name: create .ssh path
    file:
      state: directory
      path: /crockpot/.ssh
      owner: crockpot
      group: crockpot
      mode: 0700

  - name: copy authorized_keys
    copy:
      src: "{{key_path}}/tun.key.pub"
      dest: /crockpot/.ssh/authorized_keys
      mode: 0600
      owner: crockpot
      group: crockpot

  - name: copy logstash.conf
    template:
      src: logstash.conf.j2
      dest: /etc/logstash/conf.d/logstash.conf

  - name: install logstash
    apt:
      name: logstash
      state: latest

  - name: start logstash
    systemd:
      name: logstash
      state: started
      enabled: yes
