---

  - name: build directories
    file:
      path: "{{item}}"
      state: directory
      owner: crockpot
      group: crockpot
      mode: 0755
    with_items:
    - "{{glastopf_path}}"
    - "{{glastopf_path}}/logs"

  - name: config templates
    template:
      src: "{{item.s}}"
      dest: "{{item.d}}"
      owner: crockpot
      group: crockpot
      mode: 0644
    with_items:
    - { "s": "docker/Dockerfile.j2", "d": "{{glastopf_path}}/Dockerfile" }
    - { "s": "glastopf.cfg.j2", "d": "{{glastopf_path}}/glastopf.cfg" }

  - name: create local docker-compose snippet (glastopf)
    local_action:
      module: template
      src: "docker/compose-snippet.j2"
      dest: "{{playbook_dir}}/resources/glastopf.j2"

  - name: add to honeypot list
    set_fact:
      honeypots: "{{honeypots}} + [ 'glastopf' ]"

  - name: logstash directory
    file:
      path: /etc/logstash/conf.d
      recurse: true
      state: directory

  - name: glastopf logstash configuration
    template:
      src: glastopf.log.conf.j2
      dest: /etc/logstash/conf.d/glastopf.log.conf
