FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    g++ \
    gfortran \
    git \
    libevent-dev \
    liblapack-dev \
    libmysqlclient-dev \
    libxml2-dev \
    libxslt-dev \
    make \
    python-beautifulsoup \
    python-chardet \
    python-dev \
    python-gevent \
    python-lxml \
    python-openssl \
    python-pip \
    python-requests \
    python-setuptools \
    python-sqlalchemy \
    python-mysqldb \
    cython \
    python-dateutil \
    python2.7 \
    python2.7-dev \
    supervisor \
    php7.0 \
    php7.0-dev
  rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/glastopf/BFR.git /opt/BFR && \
    cd /opt/BFR && \
    phpize7.0 && \
    ./configure --enable-bfr && \
    make && \
    make install && \
    make clean && \
    cd / && \
    echo "zend_extension = "$(find /usr -name bfr.so) >> /etc/php/7.0/cli/php.ini

RUN pip install glastopf

RUN rm -rf /opt/BFR /tmp/* /var/tmp/* && \

RUN mkdir /honeypot

RUN git clone --depth 1 ${REPO} {{cowrie_path}} && \
    pip install -r {{cowrie_path}}/requirements.txt --upgrade --no-cache-dir && \
    mkdir -p {{cowrie_path}}/download && chown -R cowrie:cowrie {{cowrie_path}}

WORKDIR {{glastopf_path}}

COPY [ "cowrie.cfg", "{{cowrie_path}}" ]
CMD [ "twistd", "--nodaemon", "--umask", "0077", "--pidfile", "var/run/cowrie.pid", "cowrie" ]
