FROM ubuntu:16.04
ENV REPO https://github.com/mushorg/glastopf.git

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cython \
    g++ \
    git \
    libevent-dev \
    liblapack-dev \
    libmysqlclient-dev \
    libxml2-dev \
    libxslt-dev \
    make \
    mysql-client \
    python-dev \
    python-pip \
    python-dateutil \
    python-mysqldb \
    python-openssl \
    python-setuptools \
    php7.0 \
    php7.0-dev && \
  rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade \
    pip \
    beautifulsoup \
    chardet \
    gevent \
    lxml \
    requests \
    sqlalchemy

RUN addgroup glastopf --gid 9999 && \
    adduser glastopf --quiet --disabled-password --no-create-home --gecos "" \
      --home {{glastopf_path}} --uid 9999 --gid 9999 --shell /bin/false

RUN mkdir /honeypot

RUN git clone https://github.com/glastopf/BFR.git /opt/BFR && \
    cd /opt/BFR && \
    phpize7.0 && \
    ./configure --enable-bfr && \
    make && \
    make install && \
    make clean && \
    cd / && \
    echo "zend_extension = "$(find /usr -name bfr.so) >> /etc/php/7.0/cli/php.ini

RUN git clone ${REPO} {{glastopf_path}} && \
    cd {{glastopf_path}} && \
    python setup.py install

WORKDIR {{glastopf_path}}

COPY [ "glastopf.cfg", "{{glastopf_path}}" ]
CMD [ "python", "{{glastopf_path}}/bin/glastopf-runner" ]
