---

  - name: restart sshd
    service:
      name: ssh
      state: restarted
      enabled:  yes
    async: 0
    poll: 0
    ignore_errors: true

  - name: restart system
    command: shutdown -r now "system restarting"
    async: 0
    poll: 0
    ignore_errors: true
