---

  - name: install elastic key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: install elastic repo
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
      state: present

  - name: update system packages
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: system packages
    apt:
      name: "{{item}}"
      state: latest
    with_items:
    - apt-transport-https
    - autossh
    - ca-certificates
    - default-jre-headless
    - elasticsearch
    - logstash

  - name: locate old logstash configs
    find:
      path: /etc/logstash/conf.d
      pattern: ssh_*.conf
    register: old_cfg

  - name: remove old logstash configs
    file:
      path: "{{item.path}}"
      state: absent
    with_items: "{{old_cfg.files}}"

  - include: logstash.yml
    with_sequence: start=65001 end="{{tunnel_count|int + 65000}}"
