---

  - name: cowrie - directories
    file:
      path: "{{item}}"
      state: directory
      owner: crockpot
      group: crockpot
      mode: 0755
    with_items:
    - "{{cowrie_path}}"
    - "{{cowrie_logs}}"
    - "{{cowrie_download}}"

  - name: cowrie - Dockerfile
    template:
      src: Dockerfile.j2
      dest: "/crockpot/Dockerfile.cowrie"

  - name: cowrie - config
    template:
      src: cowrie.cfg.j2
      dest: "{{cowrie_path}}/cowrie.cfg"
