---

  - name: build directories
    file:
      path: "{{item}}"
      state: directory
      owner: crockpot
      mode: 0755
    with_items:
    - "{{cowrie_path}}"
    - "{{cowrie_path}}/logs"
    - "{{cowrie_path}}/download"

  - name: config templates
    template:
      src: "{{item.s}}"
      dest: "{{item.d}}"
      owner: crockpot
    with_items:
    - { "s": "docker/Dockerfile.j2", "d": "{{cowrie_path}}/Dockerfile" }
    - { "s": "cowrie.cfg.j2", "d": "{{cowrie_path}}/cowrie.cfg" }

  - name: create local docker-compose snippet (cowrie)
    local_action:
      module: template
      src: "docker/compose-snippet.j2"
      dest: "{{playbook_dir}}/resources/cowrie.j2"

  - name: add to honeypot list
    set_fact:
      honeypots: "{{honeypots}} + [ 'cowrie' ]"
