FROM ubuntu:16.04

ENV REPO https://github.com/DinoTools/dionaea

RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    ca-certificates \
    check \
    cython3 \
    git \
    libcurl4-openssl-dev \
    libemu-dev \
    libev-dev \
    libglib2.0-dev \
    libloudmouth1-dev \
    libnetfilter-queue-dev \
    libnl-3-200 \
    libnl-3-dev \
    libpcap-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libtool \
    libudns-dev \
    libxml2-dev \
    libxslt1-dev \
    python3 \
    python3-dev \
    python3-yaml && \
  rm -rf /var/lib/apt/lists/*

RUN addgroup dionaea --gid 9999 && \
    adduser dionaea --quiet --disabled-password --no-create-home --gecos "" \
      --home {{dionaea_path}} --uid 9999 --gid 9999 --shell /bin/false

RUN mkdir /honeypot

RUN git clone --depth 1 ${REPO} /tmp/dionaea && \
  cd /tmp/dionaea && \
  autoreconf -vi && \
  ./configure \
    --disable-werror \
    --prefix={{dionaea_path}} \
    --with-python=/usr/bin/python3 \
    --with-cython-dir=/usr/bin \
    --with-ev-include=/usr/include \
    --with-ev-lib=/usr/lib \
    --with-emu-lib=/usr/lib/libemu \
    --with-emu-include=/usr/include \
    --with-gc-include=/usr/include/gc \
    --enable-nl \
    --with-nl-include=/usr/include/libnl3 \
    --with-nl-lib=/usr/lib && \
  make && make install && \
  mkdir -p {{dionaea_path}}/logs && \
  mkdir -p {{dionaea_path}}/binaries && \
  mkdir -p {{dionaea_path}}/bistreams && \
  rm -rf {{dionaea_path}}/etc/dionaea && \
  mkdir -p {{dionaea_path}}/etc/dionaea

WORKDIR {{dionaea_path}}

COPY [ "dionaea.cfg", "{{dionaea_path}}/" ]
COPY [ "handlers/*", "{{dionaea_path}}/handlers/" ]
COPY [ "services/*", "{{dionaea_path}}/services/" ]

RUN chown -R dionaea:dionaea {{dionaea_path}}
CMD [ "{{dionaea_path}}/bin/dionaea", "-c", "{{dionaea_path}}/dionaea.cfg", "-u", "dionaea", "-g", "dionaea", "-w", "{{dionaea_path}}", "-p", "{{dionaea_path}}/var/run/dionaea.pid" ]
